In [138]:
#importing necessary lib
import pandas as pd
import numpy as np
import cv2
import glob
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [139]:
#loading training image files
imagelist_train_anim = glob.glob("animated_vs_realistic/trainset/animated/*.jpg")
imagelist_train_real = glob.glob("animated_vs_realistic/trainset/realistic/*.jpg")
new_list = glob.glob("animated_vs_realistic/new/*.jpg")

In [124]:
#loading test image files
imagelist_test_anim = glob.glob("animated_vs_realistic/testset/animated/*.jpg")
imagelist_test_real = glob.glob("animated_vs_realistic/testset/realistic//*.jpg")

In [125]:
#function for preparing real image data
def load_real_img(filelist, size=(32, 32)):
    list1 = []
    for file in filelist:
        img = cv2.imread(file, 0)
        img = cv2.resize(img, size).flatten()
        img = img/255
        img = np.insert(img, 0, 1)
        list1.append(img)
    return list1

In [126]:
#function for preparing anim image data
def load_anim_img(filelist, size=(32, 32)):
    list2 = []
    for file in filelist:
        img = cv2.imread(file, 0)
        img = cv2.resize(img, size).flatten()
        img = img/255
        img = np.insert(img, 0, 0)
        list2.append(img)
    return list2

In [127]:
#joining real and animated data to prepare dataset
def join(l1, l2):
    l = np.concatenate((l1,l2))
    return l

In [128]:
#preparing training data
real  = load_real_img(imagelist_train_real)
anim = load_anim_img(imagelist_train_anim)
train_data = join(real, anim)
train_data

array([[ 1.        ,  0.85882353,  0.8627451 , ...,  0.81960784,
         0.83921569,  0.82745098],
       [ 1.        ,  0.94509804,  0.94901961, ...,  0.4745098 ,
         0.51372549,  0.77254902],
       [ 1.        ,  0.58823529,  0.60392157, ...,  0.87843137,
         0.55686275,  0.54901961],
       ..., 
       [ 0.        ,  0.        ,  0.00392157, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.44705882,  0.29019608, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.28235294,  0.28235294, ...,  0.28235294,
         0.28235294,  0.28235294]])

In [129]:
#training feature selection
data = np.delete(train_data, 0, axis=1)
data

array([[ 0.85882353,  0.8627451 ,  0.87058824, ...,  0.81960784,
         0.83921569,  0.82745098],
       [ 0.94509804,  0.94901961,  0.94901961, ...,  0.4745098 ,
         0.51372549,  0.77254902],
       [ 0.58823529,  0.60392157,  0.61960784, ...,  0.87843137,
         0.55686275,  0.54901961],
       ..., 
       [ 0.        ,  0.00392157,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.44705882,  0.29019608,  0.25882353, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.28235294,  0.28235294,  0.28235294, ...,  0.28235294,
         0.28235294,  0.28235294]])

In [130]:
#training label extraction
label = train_data[:,0]

In [131]:
#preparing test data
real_test = load_real_img(imagelist_test_real)
anim_test = load_anim_img(imagelist_train_anim)
test_data = join(real_test, anim_test)
test_data.shape

(18, 1025)

In [132]:
#test feature selection
test_data_new = np.delete(test_data, 0, axis = 1)
test_data_new.shape

(18, 1024)

In [133]:
#test label extraction
test_label = test_data[:,0]

In [134]:
rf  =  RandomForestClassifier(max_depth= 5, n_estimators= 1100, criterion= "entropy")

In [135]:
rf.fit(data, label)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [136]:
pred  = rf.predict(test_data_new)

In [137]:
accuracy_score(test_label, pred)

0.88888888888888884

In [141]:
new = load_anim_img(new_list)
newww = np.delete(new, 0, axis=1)

In [144]:
aaaa = rf.predict(newww)

In [145]:
aaaa

array([ 0.,  0.,  0.,  1.,  0.,  0.])

In [146]:
new_list

['animated_vs_realistic/new\\55351c797f0f2edb3b8686a3e81c996a--animation-style-gif-animation.jpg',
 'animated_vs_realistic/new\\Animation-Wallpaper-23-1.jpg',
 'animated_vs_realistic/new\\download (1).jpg',
 'animated_vs_realistic/new\\download.jpg',
 'animated_vs_realistic/new\\images (1).jpg',
 'animated_vs_realistic/new\\images.jpg']